name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4.2.2

      - name: Instalar Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install cx-Freeze

      - name: Compilar con cx-Freeze
        run: python build_and_package.py
        env:
          PYTHONIOENCODING: utf-8

      - name: Obtener versión del tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Publicar release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: "SmartStitch WR ${{ steps.version.outputs.VERSION }}"
          body_path: .github/workflows/release_text.txt
          files: "SmartStitch WR-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
